apiVersion: apps/v1
kind: Deployment
metadata:
  name: clusterpulse
  labels:
    app: clusterpulse
    env: dev
    component: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: clusterpulse
      component: web
  template:
    metadata:
      labels:
        app: clusterpulse
        env: dev
        component: web
    spec:
      containers:
      - name: clusterpulse
        image: clusterpulse:dev
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000